### ISSUE TITLE
Add structure in AggregateReq/Resp to reflect when you are processing the same sub-batch

### ISSUE THREAD

**Issue by ekr** [ietf-wg-ppm/ppm-specification#109]
A batch of reports can be processed incrementally in a set of sub-batches. Each sub-batch may mean multiple RTs between leader and helper. Right now, this is hidden in the Prio or HH-specific pieces, but it probably should be manifest above.

**Comment by tgeoghegan** [comment]
Yes, it seems to me that `AggregateResp` needs a boolean in it so that helper can indicate to leader whether more rounds are needed.

**Comment by divergentdave** [comment]
I believe this has been resolved with PrepareStepResult (indicating "continued" or "finished").
