### ISSUE TITLE
How should servers figure out which task a message pertains to?

### ISSUE THREAD

**Issue by tgeoghegan** [ietf-wg-ppm/ppm-specification#146]
Aggregators are expected to have an endpoint `hpke_config` from which they vend the HPKE public key and parameters so that clients may encrypt the contents of reports. There are no parameters to the `hpke_config` request, so there is no opportunity for an aggregator to provide a different config based on the task in play.

Now, the `hpke_config` endpoint is relative to the aggregator's base endpoint URL, obtained from the per-task parameters, so an aggregator could simply provide base URLs that have the task ID in their path and use different key material on that basis. But all the other protocol messages like `Report` or `CollectReq` explicitly include task ID, suggesting that aggregators are supposed to be able to service multiple tasks from a single endpoint. Something feels inconsistent there.

**Comment by tgeoghegan** [comment]
Just for consistency, I think we could change the endpoint to `[aggregator]/hpke_config/<task_id>`. We would probably have to redefine task ID to make sure it's safe to use in URL construction (URL encoded byte strings look terrible).

**Comment by cjpatton** [comment]
Good catch, and I like your suggested fix.

**Comment by tgeoghegan** [comment]
I could swear we talked about this a long time ago. Anyway, I am putting this in `parking-lot` for now because I don't think any progress is blocked on it, and it strikes me as the kind of thing that we will go back and forth on a lot during the IETF process.

**Comment by tgeoghegan** [comment]
I think the real issue here is that when handling a message, collectors, leaders and helpers need to know which task it pertains to in order to select the appropriate HPKE context (among other parameters). We should decide whether the task ID appears in protocol messages or whether it can be inferred from the endpoint and be consistent about it.

**Comment by BranLwyd** [comment]
nit: IMO it would be more consistent to put the task ID in a `/hpke_config` request into the request body -- all other request/response pairs include the task ID in the request body, rather than including it in the request path.

(There's no technical downside to putting the task ID in the path, this is only a "consistency" concern.)

**Comment by divergentdave** [comment]
I think the issue with putting the task ID for a /hpke_config request in the body is that we have to switch from GET to POST, and lose cache-ability.

**Comment by BranLwyd** [comment]
That's a good point -- it's still pretty unsatisfying that this one request/response pair will have to be structured in this way, while all other request/response pairs (Upload, Aggregate, AggregateShare, Collect) use a different structuring.

However, given that some clients will literally be web browsers, where HTTP caching is "free", I think it's worthwhile to keep HTTP caching semantics working.

**Comment by BranLwyd** [comment]
(FWIW, this would be a great place to use [HTTP QUERY](https://www.ietf.org/id/draft-ietf-httpbis-safe-method-w-body-02.html) which is "GET but with a body", except that (a) it's still not standardized and (b) even if it were, it's still new enough that many HTTP libraries won't have good support for it.)

**Comment by BranLwyd** [comment]
One final thought for now: if we do stick to a GET request, we should consider putting the task ID for an `/hpke_config` request in a query parameter (e.g. `/hpke_config?task_id=foo`) rather than including it as part of the request path. Otherwise, every other request type will duplicate the task ID in both the request path & the request body.

**Comment by divergentdave** [comment]
The `/hpke_config` endpoint has been changed to take the task ID as a query parameter, and all other messages include a task ID in the body. Should we close this out?

**Comment by cjpatton** [comment]
Closed by #236
