### ISSUE TITLE
Sybil attack distinction

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-ppm/ppm-specification#211]
From dkg in Vienna: 

> maybe distinguish between the two kinds of sybil attacks as a sybil attack against the collector (stats poisoning), vs. a sybil attack against a reporting client (privacy violation)

**Comment by martinthomson** [comment]
It seems like there are a bunch of assumptions about Sybil attacks generally that are not well articulated yet.  This would certainly help.
