### ISSUE TITLE
OHAI proxy instead of null shares

### ISSUE THREAD

**Issue by simon-friedberger** [ietf-wg-ppm/ppm-specification#215]
It has already been mentioned that whether a client submits reports leaks. Section 6.1.2.3.4 suggests submitting "null" reports to mask this fact. 

Wouldn't it be easier to use an anonymizing proxy to hide client participation?

Also, in the case of a VDAF like heavy hitters the "null" shares would either be very obvious (random string) or create computational effort and distort the result (a semi-common prefix).

**Comment by tgeoghegan** [comment]
Our goal has been to support but not to require the use of an OHAI proxy, or any other kind of server that sits between the clients and the aggregators. There are many deployments that will want an ingestion server or a proxy for reasons ranging from client anonymization to authentication to availability, but other deployments won't want or need this.

You raise a good point about what it means to upload a null or empty report in a VDAF like Poplar1, though.

**Comment by cjpatton** [comment]
I think we should continue to support both, though the "null" report idea is a bit underspecified right now. For Poplar1, why send a random string? I would think that some fixed string (say, the all-zero string) would make more sense.

**Comment by simon-friedberger** [comment]
If you pick all-zero that string will probably always end up in your result and will have to be part of every round of the computationally-expensive protocol.

But I agree that it's probably not a huge problem even if we have to define what the null shares are for each VDAF.
