### ISSUE TITLE
Message serialization doesn't seeem fully specified

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/ppm-specification#228]
The only language I can find in the document that prescribes serialization is in Section 1.2 (please point out if I missed anything):

> This document uses the presentation language of [[RFC8446](https://datatracker.ietf.org/doc/html/rfc8446)].

We intend this statement to be prescriptive, i.e., encoding/decoding of messages is as defined in RFC8446. Another valid interpretation might be "we define the fields of each message following the conventions of RFC8446, but leaving encoding/decoding unspecified".

I think it would help to refine this statement a bit. WDYTA:

> This document uses the presentation language of RFC8446 to define messages in the PPM protocol. Encoding and decoding of these messages as byte strings also follows RFC8446.

**Comment by BranLwyd** [comment]
SGTM FWIW (this was our interpretation, and I think it makes sense to clarify)

**Comment by chris-wood** [comment]
Yeah, this seems like a fine clarification. I don't think it was under specified before, but more information for those unfamiliar with TLS-style encoding doesn't hurt.
